version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://neha-react-app-s3-bucket-123
      - aws cloudfront create-invalidation --distribution-id EWHB9ZI7W9EKZ --paths "/*"
artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes